# Generated by Django 3.0.7 on 2020-10-24 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('sort', models.PositiveSmallIntegerField(default=1, verbose_name='排序')),
                ('url', models.CharField(default='', max_length=200, verbose_name='分类地址')),
                ('num', models.PositiveSmallIntegerField(default=10, verbose_name='每次抓取数量')),
            ],
            options={
                'verbose_name': '书籍分类',
                'verbose_name_plural': '书籍分类',
                'db_table': 'book_class',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BookLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='书籍名称')),
                ('name_author_md5', models.CharField(default=0, max_length=32, verbose_name='文件夹得md5')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('cover', models.CharField(max_length=255, verbose_name='书籍封面')),
                ('url', models.CharField(max_length=255, verbose_name='书籍地址')),
                ('introduction', models.TextField(default='', verbose_name='简介')),
                ('newest_chapter', models.CharField(max_length=100, verbose_name='最新章节')),
                ('last_update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('chapter_num', models.PositiveSmallIntegerField(verbose_name='章节总数')),
                ('create_time', models.DateTimeField(verbose_name='添加时间')),
                ('last_crawling_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后爬取时间')),
                ('classification', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Book.BookClassification')),
            ],
            options={
                'verbose_name': '书籍列表',
                'verbose_name_plural': '书籍列表',
                'db_table': 'book_list',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BookSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, verbose_name='书名')),
                ('book_author', models.CharField(max_length=200, verbose_name='作者')),
                ('book_cover', models.CharField(max_length=200, verbose_name='封面')),
                ('book_url', models.CharField(max_length=200, verbose_name='地址')),
                ('book_intro', models.CharField(max_length=200, verbose_name='简介')),
                ('book_newest', models.CharField(max_length=200, verbose_name='最新章节')),
                ('book_last_update_time', models.CharField(max_length=200, verbose_name='最后更新时间')),
                ('book_chapter_list', models.CharField(max_length=200, verbose_name='章节列表')),
                ('book_chapter_list_url', models.CharField(max_length=200, verbose_name='章节列表链接')),
                ('book_chapter_info', models.CharField(max_length=200, verbose_name='章节详情')),
            ],
            options={
                'verbose_name': '书院列表',
                'verbose_name_plural': '书院列表',
                'db_table': 'book_source',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChapterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='章节内容')),
                ('words_number', models.SmallIntegerField(default=0, verbose_name='章节字数')),
                ('chapter_id', models.IntegerField(default=0, verbose_name='章节id')),
            ],
            options={
                'db_table': 'book_chapter_info',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChapterLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='章节名称')),
                ('url', models.CharField(max_length=255, verbose_name='章节地址')),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='Book.BookLists')),
            ],
            options={
                'verbose_name': '章节列表',
                'verbose_name_plural': '章节列表',
                'db_table': 'book_chapter_list',
                'ordering': ['id'],
            },
        ),
    ]
