# Generated by Django 3.0.7 on 2020-10-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20201024_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksource',
            options={'ordering': ['id'], 'verbose_name': '书源列表', 'verbose_name_plural': '书源列表'},
        ),
        migrations.AlterField(
            model_name='booksource',
            name='book_author',
            field=models.TextField(default='', max_length=200, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='booksource',
            name='book_chapter_info',
            field=models.TextField(default='', max_length=200, verbose_name='章节详情'),
        ),
        migrations.AlterField(
            model_name='booksource',
            name='book_chapter_list',
            field=models.TextField(default='', max_length=200, verbose_name='章节列表'),
        ),
        migrations.AlterField(
            model_name='booksource',
            name='book_chapter_list_url',
            field=models.TextField(default='', max_length=200, verbose_name='章节列表链接'),
        ),
        migrations.AlterField(
            model_name='booksource',
            name='book_cover',
            field=models.TextField(default='', max_length=200, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='booksource',
            name='book_intro',
            field=models.TextField(default='', max_length=200, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='booksource',
            name='book_last_update_time',
            field=models.TextField(default='', max_length=200, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='booksource',
            name='book_name',
            field=models.TextField(default='', max_length=200, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='booksource',
            name='book_newest',
            field=models.TextField(default='', max_length=200, verbose_name='最新章节'),
        ),
        migrations.AlterField(
            model_name='booksource',
            name='book_url',
            field=models.TextField(default='', max_length=200, verbose_name='地址'),
        ),
    ]
