# Generated by Django 3.0.7 on 2020-10-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_auto_20201024_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksource',
            name='book_name',
        ),
        migrations.AddField(
            model_name='booksource',
            name='book_info',
            field=models.TextField(default='', max_length=200, verbose_name='书籍信息(逗号分隔,书名，作者，最新章，时间)'),
        ),
    ]
