# Generated by Django 3.0.7 on 2020-10-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_auto_20201024_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksource',
            name='book_info_common',
            field=models.TextField(default='', max_length=200, verbose_name='书籍信息公共链接'),
        ),
    ]
