# Generated by Django 3.0.7 on 2020-10-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_booksource_book_info_common'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksource',
            name='book_url',
        ),
        migrations.AlterField(
            model_name='booksource',
            name='book_info',
            field=models.TextField(default='', max_length=200, verbose_name='书籍信息(逗号分隔,书名，地址，作者，最新章，时间)'),
        ),
    ]
