# Generated by Django 3.0.7 on 2020-10-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0008_auto_20201024_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksource',
            name='book_last_time',
            field=models.TextField(default='', verbose_name='最后更新时间'),
        ),
    ]
